/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bioclim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bioclim */
        get: operations["getBioclimInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Species
         * @description Resolve free text to canonical GBIF backbone taxon keys, enriched with iNat metadata.
         */
        get: operations["searchSpecies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Species */
        get: operations["listSpecies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Species */
        get: operations["getSpecies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Pipeline
         * @description Enqueue the incremental-fetch / conditional-retrain pipeline (full run if new).
         */
        post: operations["runSpeciesPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Project Scenarios
         * @description Project the current model onto registered climate scenarios (no retraining).
         */
        post: operations["projectScenarios"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/crosscheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Crosscheck
         * @description Refit the current model on the independent cross-check climate stack (e.g. CHELSA).
         */
        post: operations["runClimateCrossCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/hires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Project Hires
         * @description Project the current model at high resolution (e.g. 30″) inside a region.
         */
        post: operations["projectHighResolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/native-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Native Range */
        get: operations["getNativeRange"];
        /**
         * Put Native Range
         * @description Save a user-reviewed polygon. Confirming it unlocks (re)training.
         */
        put: operations["updateNativeRange"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/occurrences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Occurrences
         * @description Paginated occurrence list for table views (map layers use pg_tileserv vector tiles).
         */
        get: operations["listOccurrences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/occurrences/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Occurrence Timeline */
        get: operations["getOccurrenceTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/severity-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Severity Config
         * @description Update the severity weights/priors and re-weight the current model's components
         *     (no retraining; returns null if no model exists yet).
         */
        put: operations["updateSeverityConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description All model versions, newest first, with full reproducibility metadata.
         */
        get: operations["listModelVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/models/{model_version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["getModelVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layers */
        get: operations["getLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/bulletin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulletin Status */
        get: operations["getBulletinStatus"];
        put?: never;
        /** Generate */
        post: operations["generateBulletin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/species/{taxon_key}/bulletin/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["downloadBulletin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Jobs
         * @description Live job list for a species (or all jobs): replaces client polling while connected.
         */
        get: operations["streamJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Report */
        get: operations["getValidationReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["runValidationSuite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BackgroundInfo */
        BackgroundInfo: {
            /**
             * Method
             * @description Method actually used, e.g. target_group_order, buffer_500km
             */
            method: string;
            /** Requested Method */
            requested_method: string;
            /** Buffer Km */
            buffer_km: number;
            target_group?: components["schemas"]["TargetGroupInfo"] | null;
            /**
             * Fallback Reason
             * @description Why target-group background was not used, if it was requested
             */
            fallback_reason?: string | null;
        };
        /** BioclimInfo */
        BioclimInfo: {
            /** Version */
            version: string;
            /** Source */
            source: string;
            /** Resolution */
            resolution: string;
            /** Selected Predictors */
            selected_predictors: string[];
            /** Vif */
            vif: {
                [key: string]: number;
            };
            /** Descriptions */
            descriptions: {
                [key: string]: string;
            };
            /** Scenarios */
            scenarios: string[];
            /** Citation */
            citation?: string | null;
            /** Hires Resolutions */
            hires_resolutions?: string[];
            /**
             * Crosscheck Version
             * @description Independent climate stack used for the climate-data cross-check
             */
            crosscheck_version?: string | null;
            /** Crosscheck Source */
            crosscheck_source?: string | null;
        };
        /** BulletinRequest */
        BulletinRequest: {
            /** Model Version */
            model_version?: number | null;
        };
        /** BulletinStatus */
        BulletinStatus: {
            /** Taxon Key */
            taxon_key: number;
            /** Model Version */
            model_version: number | null;
            /** Pdf Available */
            pdf_available: boolean;
            /** Html Available */
            html_available: boolean;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Html Url */
            html_url?: string | null;
        };
        /**
         * ClimateCrossCheckOut
         * @description The model version refitted on an independent climate source (same training points,
         *     feature classes, regularisation and CV seed) and compared with the original.
         */
        ClimateCrossCheckOut: {
            /** Alt Bioclim Version */
            alt_bioclim_version: string;
            /** Alt Source */
            alt_source: string;
            /** Primary Bioclim Version */
            primary_bioclim_version: string;
            /** Created Ts */
            created_ts: string;
            /** N Presence */
            n_presence: number;
            /** N Background */
            n_background: number;
            /**
             * N Dropped
             * @description Training points without data in the alternative stack
             */
            n_dropped: number;
            /** Feature Classes */
            feature_classes: string;
            /** Beta Multiplier */
            beta_multiplier: number;
            /** Predictors */
            predictors: components["schemas"]["PredictorAgreementOut"][];
            primary: components["schemas"]["CrossCheckMetricsOut"];
            alternative: components["schemas"]["CrossCheckMetricsOut"];
            /**
             * Suitability Rank Correlation
             * @description Spearman ρ of the two models' suitability at the training points
             */
            suitability_rank_correlation: number | null;
            /** Classification Agreement */
            classification_agreement: number | null;
            /** Classification Kappa */
            classification_kappa: number | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "consistent" | "moderate" | "divergent";
            /** Interpretation */
            interpretation: string;
        };
        /** CrossCheckMetricsOut */
        CrossCheckMetricsOut: {
            /** Auc Mean */
            auc_mean?: number | null;
            /** Cbi Mean */
            cbi_mean?: number | null;
            /** Tss Mean */
            tss_mean?: number | null;
            /** Threshold */
            threshold?: number | null;
        };
        /** FoldMetricsOut */
        FoldMetricsOut: {
            /** Fold */
            fold: number;
            /** N Train Presence */
            n_train_presence: number;
            /** N Test Presence */
            n_test_presence: number;
            /** N Test Background */
            n_test_background: number;
            /** Auc */
            auc: number | null;
            /** Tss */
            tss: number | null;
            /** Cbi */
            cbi: number | null;
        };
        /** GeoJSONMultiPolygon */
        GeoJSONMultiPolygon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultiPolygon";
            /** Coordinates */
            coordinates: number[][][][];
        };
        /** GeoJSONPolygon */
        GeoJSONPolygon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: number[][][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Bioclim Version */
            bioclim_version: string;
            /** Bioclim Available */
            bioclim_available: boolean;
        };
        /**
         * HiresLayer
         * @description Regional high-resolution projection of the same model (no retraining).
         */
        HiresLayer: {
            /** Resolution */
            resolution: string;
            /**
             * Bbox
             * @description [west, south, east, north] of the projected region
             */
            bbox: number[];
            suitability: components["schemas"]["RasterLayer"];
            /** @description This region's own MESS < 0 mask */
            extrapolation: components["schemas"]["RasterLayer"];
            /** Extrapolated Land Fraction */
            extrapolated_land_fraction?: number | null;
            /** Created Ts */
            created_ts: string;
        };
        /** HiresRequest */
        HiresRequest: {
            /**
             * Bbox
             * @description [west, south, east, north] in degrees
             */
            bbox: number[];
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "pipeline" | "bulletin" | "scenarios" | "validation" | "crosscheck" | "hires";
        /** JobOut */
        JobOut: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Taxon Key */
            taxon_key: number | null;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            /** Stage */
            stage?: string | null;
            /** Progress */
            progress: number;
            /** Message */
            message?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created Ts
             * Format: date-time
             */
            created_ts: string;
            /**
             * Updated Ts
             * Format: date-time
             */
            updated_ts: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** LayerCaveats */
        LayerCaveats: {
            /**
             * Model Type
             * @enum {string}
             */
            model_type: "A" | "B";
            /**
             * Confidence Label
             * @enum {string}
             */
            confidence_label: "standard" | "lower";
            /** Transferability Caveat */
            transferability_caveat: string;
            /**
             * Mess Required
             * @default true
             */
            mess_required: boolean;
        };
        /** LayerSet */
        LayerSet: {
            /** Taxon Key */
            taxon_key: number;
            /** Model Version */
            model_version: number | null;
            occurrences: components["schemas"]["VectorLayer"];
            native_range: components["schemas"]["VectorLayer"];
            suitability?: components["schemas"]["RasterLayer"] | null;
            mess?: components["schemas"]["RasterLayer"] | null;
            zones?: components["schemas"]["RasterLayer"] | null;
            /** @description MESS < 0 mask; always offered as an overlay with any projection */
            extrapolation?: components["schemas"]["RasterLayer"] | null;
            /** Scenarios */
            scenarios?: components["schemas"]["ScenarioLayer"][];
            /**
             * Scenarios Available
             * @description Scenarios registered for the model's bioclim version (projected or not)
             */
            scenarios_available?: string[];
            hires?: components["schemas"]["HiresLayer"] | null;
            /**
             * Hires Available
             * @description Resolution of the model's high-resolution stack, if one is registered
             */
            hires_available?: string | null;
            /** Hires Max Cells */
            hires_max_cells?: number | null;
            caveats?: components["schemas"]["LayerCaveats"] | null;
        };
        /** LegendEntry */
        LegendEntry: {
            /** Value */
            value: number;
            /** Color */
            color: string;
            /** Label */
            label: string;
        };
        /** ModelSummary */
        ModelSummary: {
            /** Model Version */
            model_version: number;
            /**
             * Model Type
             * @enum {string}
             */
            model_type: "A" | "B";
            /**
             * Confidence Label
             * @enum {string}
             */
            confidence_label: "standard" | "lower";
            /**
             * Trained Ts
             * Format: date-time
             */
            trained_ts: string;
            /** Trigger */
            trigger: string;
            /** Auc Mean */
            auc_mean?: number | null;
            /** Cbi Mean */
            cbi_mean?: number | null;
            /** Tss Mean */
            tss_mean?: number | null;
            /** Transferability Caveat */
            transferability_caveat: string;
            severity?: components["schemas"]["SeverityResult"] | null;
        };
        /** ModelVersionDetail */
        ModelVersionDetail: {
            /** Model Version */
            model_version: number;
            /**
             * Model Type
             * @enum {string}
             */
            model_type: "A" | "B";
            /**
             * Confidence Label
             * @enum {string}
             */
            confidence_label: "standard" | "lower";
            /**
             * Trained Ts
             * Format: date-time
             */
            trained_ts: string;
            /** Trigger */
            trigger: string;
            /** Auc Mean */
            auc_mean?: number | null;
            /** Auc Std */
            auc_std?: number | null;
            /** Cbi Mean */
            cbi_mean?: number | null;
            /** Cbi Std */
            cbi_std?: number | null;
            /** Tss Mean */
            tss_mean?: number | null;
            /** Tss Std */
            tss_std?: number | null;
            /** N Presence */
            n_presence: number;
            /** N Background */
            n_background: number;
            /** N Cv Folds */
            n_cv_folds: number;
            /** Feature Classes */
            feature_classes: string;
            /** Beta Multiplier */
            beta_multiplier: number;
            /** Severity Score */
            severity_score?: number | null;
            /** Mlflow Run Id */
            mlflow_run_id?: string | null;
            reproducibility: components["schemas"]["ReproducibilityInfo"];
            /** Threshold */
            threshold: number;
            /** Threshold Rule */
            threshold_rule: string;
            /** Cv Method */
            cv_method: string;
            /** Predictors */
            predictors: string[];
            /** Variable Importance */
            variable_importance: {
                [key: string]: number;
            };
            /** Folds */
            folds: components["schemas"]["FoldMetricsOut"][];
            /** Tuning */
            tuning: {
                [key: string]: unknown;
            }[];
            projection: components["schemas"]["ProjectionSummaryOut"];
            /** Transferability Caveat */
            transferability_caveat: string;
            severity?: components["schemas"]["SeverityResult"] | null;
            /** N Records By Effective Label */
            n_records_by_effective_label: {
                [key: string]: number;
            };
            /** Crosschecks */
            crosschecks?: components["schemas"]["ClimateCrossCheckOut"][];
        };
        /** ModelVersionOut */
        ModelVersionOut: {
            /** Model Version */
            model_version: number;
            /**
             * Model Type
             * @enum {string}
             */
            model_type: "A" | "B";
            /**
             * Confidence Label
             * @enum {string}
             */
            confidence_label: "standard" | "lower";
            /**
             * Trained Ts
             * Format: date-time
             */
            trained_ts: string;
            /** Trigger */
            trigger: string;
            /** Auc Mean */
            auc_mean?: number | null;
            /** Auc Std */
            auc_std?: number | null;
            /** Cbi Mean */
            cbi_mean?: number | null;
            /** Cbi Std */
            cbi_std?: number | null;
            /** Tss Mean */
            tss_mean?: number | null;
            /** Tss Std */
            tss_std?: number | null;
            /** N Presence */
            n_presence: number;
            /** N Background */
            n_background: number;
            /** N Cv Folds */
            n_cv_folds: number;
            /** Feature Classes */
            feature_classes: string;
            /** Beta Multiplier */
            beta_multiplier: number;
            /** Severity Score */
            severity_score?: number | null;
            /** Mlflow Run Id */
            mlflow_run_id?: string | null;
            reproducibility: components["schemas"]["ReproducibilityInfo"];
        };
        /** NativeRangeOut */
        NativeRangeOut: {
            /** Taxon Key */
            taxon_key: number;
            geometry: components["schemas"]["GeoJSONMultiPolygon"];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "confirmed";
            /** Source */
            source: string;
            /** Note */
            note?: string | null;
            /**
             * Updated Ts
             * Format: date-time
             */
            updated_ts: string;
            /** Confirmed Ts */
            confirmed_ts?: string | null;
        };
        /** NativeRangeUpdate */
        NativeRangeUpdate: {
            /** Geometry */
            geometry: components["schemas"]["GeoJSONPolygon"] | components["schemas"]["GeoJSONMultiPolygon"];
            /**
             * Confirm
             * @description Mark as user-reviewed; required before training
             * @default false
             */
            confirm: boolean;
            /** Note */
            note?: string | null;
            /**
             * Train
             * @description Enqueue a pipeline run after confirming
             * @default false
             */
            train: boolean;
        };
        /** NativeRangeUpdateResult */
        NativeRangeUpdateResult: {
            native_range: components["schemas"]["NativeRangeOut"];
            job?: components["schemas"]["JobOut"] | null;
        };
        /** OccurrencePage */
        OccurrencePage: {
            /** Items */
            items: components["schemas"]["OccurrenceRow"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** OccurrenceRow */
        OccurrenceRow: {
            /**
             * Source
             * @enum {string}
             */
            source: "GBIF" | "iNaturalist";
            /** Record Id */
            record_id: number;
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
            /** Event Date */
            event_date?: string | null;
            /** Coordinate Uncertainty M */
            coordinate_uncertainty_m?: number | null;
            /** Basis Of Record */
            basis_of_record?: string | null;
            /** Country Code */
            country_code?: string | null;
            /**
             * Range Label
             * @enum {string}
             */
            range_label: "native" | "introduced" | "unknown";
            /**
             * Ingested Ts
             * Format: date-time
             */
            ingested_ts: string;
        };
        /**
         * OccurrenceSources
         * @description How the merged occurrence set was assembled (records are de-duplicated across sources).
         */
        OccurrenceSources: {
            /**
             * Gbif
             * @description Records ingested from GBIF
             */
            gbif: number;
            /**
             * Gbif From Inaturalist
             * @description Subset of the GBIF records that are iNaturalist research-grade observations republished to GBIF (linked by inat_crossref_id)
             */
            gbif_from_inaturalist: number;
            /**
             * Inaturalist Direct
             * @description Research-grade observations fetched from iNaturalist and not yet in GBIF
             */
            inaturalist_direct: number;
            /** Last Inat Fetch Ts */
            last_inat_fetch_ts?: string | null;
        };
        /** PredictorAgreementOut */
        PredictorAgreementOut: {
            /** Predictor */
            predictor: string;
            /** Pearson R */
            pearson_r: number | null;
            /**
             * Mean Diff
             * @description Mean of (alternative − primary)
             */
            mean_diff: number | null;
            /** Mean Abs Diff */
            mean_abs_diff: number | null;
            /**
             * Scale Ratio
             * @description Median |alternative| / median |primary|; far from 1 suggests a unit mismatch
             */
            scale_ratio: number | null;
            /** Units Suspect */
            units_suspect: boolean;
        };
        /** ProjectionSummaryOut */
        ProjectionSummaryOut: {
            /** Land Area Km2 */
            land_area_km2: number;
            /** Nonnative Land Area Km2 */
            nonnative_land_area_km2: number;
            /** Native Suitable Area Km2 */
            native_suitable_area_km2: number;
            /** Established Outside Area Km2 */
            established_outside_area_km2: number;
            /** Candidate Area Km2 */
            candidate_area_km2: number;
            /** Candidate Mean Suitability */
            candidate_mean_suitability: number;
            /** Candidate Fraction Of Nonnative Land */
            candidate_fraction_of_nonnative_land: number;
            /** Candidate Mess Ok Fraction */
            candidate_mess_ok_fraction: number;
            /** Candidate Envelope Fraction */
            candidate_envelope_fraction: number;
            /** Extrapolation Area Km2 */
            extrapolation_area_km2: number;
            /** Top Candidate Regions */
            top_candidate_regions: {
                [key: string]: unknown;
            }[];
            /** Top Limiting Variables */
            top_limiting_variables: {
                [key: string]: unknown;
            }[];
        };
        /** RasterLayer */
        RasterLayer: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Tile Url
             * @description XYZ template with {z}/{x}/{y}
             */
            tile_url: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "continuous" | "categorical";
            /** Legend */
            legend: components["schemas"]["LegendEntry"][];
            /** Description */
            description: string;
        };
        /** ReproducibilityInfo */
        ReproducibilityInfo: {
            /** Bioclim Version Used */
            bioclim_version_used: string;
            /** Bioclim Source */
            bioclim_source?: string | null;
            /** Bioclim Sha256 */
            bioclim_sha256?: string | null;
            /**
             * Bioclim Dvc Md5
             * @description DVC hash of the bioclim version directory (data/bioclim/<v>.dvc)
             */
            bioclim_dvc_md5?: string | null;
            /** Gbif Download Key */
            gbif_download_key?: string | null;
            /** Gbif Download Doi */
            gbif_download_doi?: string | null;
            /** Gbif Citation */
            gbif_citation: string;
            /** Inat Citation */
            inat_citation?: string | null;
            /** Package Versions */
            package_versions: {
                [key: string]: string;
            };
            /** Random Seeds */
            random_seeds: {
                [key: string]: number;
            };
            /** Training Config */
            training_config: {
                [key: string]: unknown;
            };
            /** Native Range Source */
            native_range_source: string;
            /** Native Range Confirmed Ts */
            native_range_confirmed_ts?: string | null;
            /** @description Background sampling record; absent for versions trained before it */
            background?: components["schemas"]["BackgroundInfo"] | null;
            /** @description Exact MaxEnt input (presences + background with predictors); absent for versions trained before snapshots were introduced */
            training_data?: components["schemas"]["TrainingSnapshotInfo"] | null;
            /** @description All valid records considered, with ingested and effective labels */
            occurrence_manifest?: components["schemas"]["TrainingSnapshotInfo"] | null;
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Force Retrain
             * @default false
             */
            force_retrain: boolean;
            /**
             * Full Resync
             * @description Re-fetch all records (not only the delta) and append missing ones
             * @default false
             */
            full_resync: boolean;
        };
        /** ScenarioLayer */
        ScenarioLayer: {
            /**
             * Id
             * @description 'scenario:<name>'
             */
            id: string;
            /** Name */
            name: string;
            /** Label */
            label: string;
            suitability: components["schemas"]["RasterLayer"];
            /** @description This scenario's own MESS < 0 mask (null for legacy projections) */
            extrapolation?: components["schemas"]["RasterLayer"] | null;
            /** Extrapolated Land Fraction */
            extrapolated_land_fraction?: number | null;
        };
        /** SeverityComponents */
        SeverityComponents: {
            /** Suitability */
            suitability: number;
            /** Climate Analogy */
            climate_analogy: number;
            /** Spread Rate */
            spread_rate: number;
            /** Ecological Impact Prior */
            ecological_impact_prior: number;
        };
        /** SeverityConfidence */
        SeverityConfidence: {
            /**
             * Level
             * @enum {string}
             */
            level: "low" | "moderate" | "high";
            /** Mess Ok Fraction */
            mess_ok_fraction: number;
            /**
             * Model Type
             * @enum {string}
             */
            model_type: "A" | "B";
            /** Note */
            note: string;
        };
        /** SeverityConfigModel */
        SeverityConfigModel: {
            weights?: components["schemas"]["SeverityWeights"];
            /**
             * Impact Prior
             * @default 0.5
             */
            impact_prior: number;
            /**
             * Impact Prior Source
             * @default default (unknown)
             */
            impact_prior_source: string;
            /**
             * Suitability Saturation
             * @default 0.1
             */
            suitability_saturation: number;
            /**
             * Spread Half Saturation
             * @default 5
             */
            spread_half_saturation: number;
            /**
             * Spread Window Years
             * @default 10
             */
            spread_window_years: number;
        };
        /** SeverityResult */
        SeverityResult: {
            /** Score */
            score: number;
            /** Score 0 100 */
            score_0_100: number;
            /**
             * Category
             * @enum {string}
             */
            category: "low" | "moderate" | "high" | "very high";
            components: components["schemas"]["SeverityComponents"];
            weights: components["schemas"]["SeverityComponents"];
            contributions: components["schemas"]["SeverityComponents"];
            /** Descriptions */
            descriptions: {
                [key: string]: string;
            };
            confidence: components["schemas"]["SeverityConfidence"];
            /** Formula */
            formula: string;
            config: components["schemas"]["SeverityConfigModel"];
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
        };
        /** SeverityWeights */
        SeverityWeights: {
            /**
             * Suitability
             * @default 0.35
             */
            suitability: number;
            /**
             * Climate Analogy
             * @default 0.25
             */
            climate_analogy: number;
            /**
             * Spread Rate
             * @default 0.2
             */
            spread_rate: number;
            /**
             * Ecological Impact Prior
             * @default 0.2
             */
            ecological_impact_prior: number;
        };
        /** SpeciesDetail */
        SpeciesDetail: {
            /** Taxon Key */
            taxon_key: number;
            /** Scientific Name */
            scientific_name: string;
            /** Common Name */
            common_name?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            status: components["schemas"]["SpeciesStatus"];
            /** N Occurrences Total */
            n_occurrences_total: number;
            /** N Occurrences Native */
            n_occurrences_native: number;
            /** N Pending Records */
            n_pending_records: number;
            /** Model Version */
            model_version: number;
            /** Model Trained Ts */
            model_trained_ts?: string | null;
            /** Last Gbif Fetch Ts */
            last_gbif_fetch_ts?: string | null;
            /** Retrain Needed */
            retrain_needed: boolean;
            /**
             * Severity Score
             * @description 0–100, current model
             */
            severity_score?: number | null;
            /** Model Type */
            model_type?: ("A" | "B") | null;
            /** Canonical Name */
            canonical_name?: string | null;
            /** Inat Taxon Id */
            inat_taxon_id?: number | null;
            /** Last Gbif Download Key */
            last_gbif_download_key?: string | null;
            /** Last Gbif Download Doi */
            last_gbif_download_doi?: string | null;
            /** Bioclim Version Used */
            bioclim_version_used?: string | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Native Range Status
             * @enum {string}
             */
            native_range_status: "missing" | "draft" | "confirmed";
            sources: components["schemas"]["OccurrenceSources"];
            current_model?: components["schemas"]["ModelSummary"] | null;
            severity_config: components["schemas"]["SeverityConfigModel"];
        };
        /**
         * SpeciesStatus
         * @description Lifecycle state surfaced to the frontend as status badges.
         * @enum {string}
         */
        SpeciesStatus: "registered" | "ingesting" | "awaiting_native_range_review" | "training" | "up_to_date" | "minor_update_pending" | "retrain_pending" | "failed";
        /** SpeciesSummary */
        SpeciesSummary: {
            /** Taxon Key */
            taxon_key: number;
            /** Scientific Name */
            scientific_name: string;
            /** Common Name */
            common_name?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            status: components["schemas"]["SpeciesStatus"];
            /** N Occurrences Total */
            n_occurrences_total: number;
            /** N Occurrences Native */
            n_occurrences_native: number;
            /** N Pending Records */
            n_pending_records: number;
            /** Model Version */
            model_version: number;
            /** Model Trained Ts */
            model_trained_ts?: string | null;
            /** Last Gbif Fetch Ts */
            last_gbif_fetch_ts?: string | null;
            /** Retrain Needed */
            retrain_needed: boolean;
            /**
             * Severity Score
             * @description 0–100, current model
             */
            severity_score?: number | null;
            /** Model Type */
            model_type?: ("A" | "B") | null;
        };
        /** TargetGroupInfo */
        TargetGroupInfo: {
            /** Rank */
            rank: string;
            /**
             * Taxon Key
             * @description GBIF key of the target group (e.g. the species' order)
             */
            taxon_key: number;
            /** Name */
            name: string;
            /**
             * N Records
             * @description GBIF records of the target group in the region
             */
            n_records: number;
            /** N Pixels */
            n_pixels: number;
            /** Map Zoom */
            map_zoom: number;
            /** Pixel Deg */
            pixel_deg: number;
            /** N Tiles */
            n_tiles: number;
            /**
             * Query
             * @description GBIF map API density-tile query used as sampling effort
             */
            query: string;
            /** Fetched Ts */
            fetched_ts: string;
        };
        /** TaxonSearchResult */
        TaxonSearchResult: {
            /** Taxon Key */
            taxon_key: number;
            /** Scientific Name */
            scientific_name: string;
            /** Canonical Name */
            canonical_name?: string | null;
            /** Rank */
            rank?: string | null;
            /**
             * Breadcrumb
             * @description Kingdom → genus
             */
            breadcrumb?: string[];
            /** Common Name */
            common_name?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Inat Taxon Id */
            inat_taxon_id?: number | null;
            /**
             * In Registry
             * @default false
             */
            in_registry: boolean;
            status?: components["schemas"]["SpeciesStatus"] | null;
        };
        /** Timeline */
        Timeline: {
            /** Years */
            years: components["schemas"]["TimelineYear"][];
            /** Min Year */
            min_year: number | null;
            /** Max Year */
            max_year: number | null;
        };
        /** TimelineYear */
        TimelineYear: {
            /** Year */
            year: number;
            /** Native */
            native: number;
            /** Introduced */
            introduced: number;
            /** Unknown */
            unknown: number;
            /** Cumulative */
            cumulative: number;
        };
        /**
         * TrainingSnapshotInfo
         * @description A per-version, content-addressed data file (see training_snapshot.py).
         */
        TrainingSnapshotInfo: {
            /**
             * Path
             * @description Artifact path, relative to the artifact root
             */
            path: string;
            /** Sha256 */
            sha256: string;
            /** N Rows */
            n_rows: number;
            /** Bytes */
            bytes: number;
        };
        /** TransferabilityResult */
        TransferabilityResult: {
            /** Auc */
            auc?: number | null;
            /** Cbi */
            cbi?: number | null;
            /** N Native Train */
            n_native_train?: number | null;
            /** N Introduced Test */
            n_introduced_test?: number | null;
            /** Literature Mean Auc */
            literature_mean_auc?: number | null;
            /** Method */
            method?: string | null;
            /** Skipped */
            skipped?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationRegion */
        ValidationRegion: {
            /** Name */
            name: string;
            /** Bbox */
            bbox: number[];
            /**
             * Expect
             * @enum {string}
             */
            expect: "suitable" | "unsuitable";
            /** Ref */
            ref: string;
            /** Fraction Suitable */
            fraction_suitable?: number | null;
            /** Mean Suitability */
            mean_suitability?: number | null;
            /** Passed */
            passed: boolean;
        };
        /** ValidationReport */
        ValidationReport: {
            /**
             * Generated Ts
             * Format: date-time
             */
            generated_ts: string;
            /** Criteria */
            criteria: {
                [key: string]: unknown;
            };
            /** Species */
            species: components["schemas"]["ValidationSpecies"][];
            summary: components["schemas"]["ValidationSummary"];
        };
        /** ValidationRunRequest */
        ValidationRunRequest: {
            /**
             * Taxon Keys
             * @description Subset of reference species
             */
            taxon_keys?: number[] | null;
            /**
             * Train
             * @description Ingest/train reference species that lack a model
             * @default true
             */
            train: boolean;
        };
        /** ValidationSpecies */
        ValidationSpecies: {
            /** Taxon Key */
            taxon_key: number;
            /** Scientific Name */
            scientific_name: string;
            /** Native Range Reference */
            native_range_reference: string;
            /**
             * Status
             * @enum {string}
             */
            status: "evaluated" | "no_model" | "error";
            /** Passed */
            passed: boolean;
            /** Error */
            error?: string | null;
            /** Model Version */
            model_version?: number | null;
            /** Model Type */
            model_type?: ("A" | "B") | null;
            /** Bioclim Version */
            bioclim_version?: string | null;
            /** Auc Mean */
            auc_mean?: number | null;
            /** Cbi Mean */
            cbi_mean?: number | null;
            /** Tss Mean */
            tss_mean?: number | null;
            /** N Occurrences */
            n_occurrences?: number | null;
            /** Regions */
            regions?: components["schemas"]["ValidationRegion"][];
            /** Invaded Captured */
            invaded_captured?: number | null;
            /** Invaded Total */
            invaded_total?: number | null;
            /** Controls Correct */
            controls_correct?: number | null;
            /** Controls Total */
            controls_total?: number | null;
            transferability?: components["schemas"]["TransferabilityResult"] | null;
        };
        /** ValidationSummary */
        ValidationSummary: {
            /** N Species */
            n_species: number;
            /** N Passed */
            n_passed: number;
            /** Mean Transfer Auc */
            mean_transfer_auc?: number | null;
            /** Literature Mean Transfer Auc */
            literature_mean_transfer_auc: number;
        };
        /** VectorLayer */
        VectorLayer: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Tile Url
             * @description MVT XYZ template; extra query params may be appended
             */
            tile_url: string;
            /** Source Layer */
            source_layer: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getBioclimInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BioclimInfo"];
                };
            };
        };
    };
    searchSpecies: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSpecies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesSummary"][];
                };
            };
        };
    };
    getSpecies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runSpeciesPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projectScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runClimateCrossCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projectHighResolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HiresRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getNativeRange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeRangeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateNativeRange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeRangeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeRangeUpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listOccurrences: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                source?: ("GBIF" | "iNaturalist") | null;
                range_label?: ("native" | "introduced" | "unknown") | null;
            };
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccurrencePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getOccurrenceTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateSeverityConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeverityConfigModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeverityResult"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listModelVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getModelVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
                model_version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getLayers: {
        parameters: {
            query?: {
                model_version?: number | null;
            };
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerSet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getBulletinStatus: {
        parameters: {
            query?: {
                model_version?: number | null;
            };
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulletinStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generateBulletin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BulletinRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    downloadBulletin: {
        parameters: {
            query?: {
                format?: "pdf" | "html";
                model_version?: number | null;
            };
            header?: never;
            path: {
                taxon_key: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                    "text/html": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streamJobs: {
        parameters: {
            query?: {
                taxon_key?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of `jobs` events; each `data:` line is a JSON array of JobOut (newest first, same as GET /jobs), sent on connect and on change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                taxon_key?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getValidationReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
        };
    };
    runValidationSuite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ValidationRunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
